Write-Host ""
Write-Host "=== VATA DEMO COMMANDS ==="
Write-Host ""
Write-Host "1) Verify (local + onchain):"
Write-Host "   .\RUN_DEMO.ps1"
Write-Host ""
Write-Host "2) Tamper test (prove it fails if receipt.json is changed):"
Write-Host "   powershell -NoProfile -ExecutionPolicy Bypass -File .\TAMPER_TEST.ps1"
Write-Host ""
Write-Host "3) Anchor current root on OP Sepolia (writes anchor_tx.txt):"
Write-Host "   powershell -NoProfile -ExecutionPolicy Bypass -File .\ANCHOR_ROOT_OPSEPOLIA.ps1"
Write-Host ""
Write-Host "Repo: https://github.com/LHMisme420/vata-demo-epoch-0001"
Write-Host ""
